services:
  # -----------------------------------------------------
  # 1. 예약용 Redis (REDIS_BOOK)
  # -----------------------------------------------------
  redis-book:
    image: redis:alpine
    container_name: redis-book
    profiles: ['redis', 'all']
    ports:
      - '6379:6379'
    command: redis-server --requirepass "${REDIS_PASSWORD_BOOK}" --appendonly yes
    volumes:
      - ./redis-data/book:/data
    networks:
      - backend-net

  # -----------------------------------------------------
  # 2. 대기열용 Redis (REDIS_WAIT)
  # -----------------------------------------------------
  redis-wait:
    image: redis:alpine
    container_name: redis-wait
    profiles: ['redis', 'all']
    ports:
      - '6380:6379'
    command: redis-server --requirepass "${REDIS_PASSWORD_WAIT}" --appendonly yes
    volumes:
      - ./redis-data/wait:/data
    networks:
      - backend-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    profiles: ['db', 'all']
    restart: always
    environment:
      # 추후 env로 변경
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: backend_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - backend-net
networks:
  backend-net:
    driver: bridge
